/* Run with temporary playwright-core on NODE_PATH; use installed Edge. */
const { chromium } = require('playwright-core');
const path = require('path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const base = 'http://127.0.0.1:8000/';
  const routes = ['#/', '#/explorer', '#/explorer?coverage=1', '#/compare?a=BASS2-T101&b=BASS2-T102&factor=airflow_cms', '#/compare?a=BASS2-T101&b=BASS2-T137&factor=airflow_cms', '#/evidence/BASS2-T124', '#/record/BASS2-T133', '#/data-notes'];
  let layouts = 0;
  for (const width of [320,375,390,430,768,1024,1280,1440,1920]) {
    await page.setViewportSize({ width, height: 1000 });
    for (const route of routes) {
      await page.goto(base + route);
      await page.locator('main h1').waitFor();
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
      assert.equal(overflow, false, `Horizontal overflow at ${width}: ${route}`);
      layouts++;
    }
  }
  console.log(`PASS ${layouts} route/viewport layouts without page overflow`);
  await page.setViewportSize({width: 390, height: 844});
  await page.goto(base + '#/explorer');
  await page.locator('#explorer-search').fill('no-such-experiment');
  await page.waitForTimeout(250);
  await page.getByText('No records match the current filters', {exact: true}).waitFor();
  await page.locator('#search-clear').click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'explorer-search');
  assert.equal(await page.locator('.record-card').count(), await page.evaluate(() => CinderLens.CATALOG.length));
  await page.locator('[data-action="toggle-filters"]').click();
  assert.equal(await page.locator('#filters').getAttribute('aria-modal'), 'true');
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(() => document.activeElement.closest('#filters') !== null), true);
  await page.locator('[data-quickband="thickness"][data-value="3.2"]').click();
  assert.equal(await page.evaluate(() => document.activeElement.dataset.quickband), 'thickness');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => document.activeElement.closest('#filters') !== null), true);
  await page.locator('#filters [data-action="clear-filters"]').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('[data-action="toggle-filters"]').getAttribute('aria-expanded'), 'false');
  assert.equal(await page.evaluate(() => document.activeElement.dataset.action), 'toggle-filters');
  await page.locator('#nav-toggle').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#nav-toggle').getAttribute('aria-expanded'), 'false');
  await page.locator('.skip-link').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'main');
  assert.match(page.url(), /#\/explorer$/);
  await page.locator('.record-card [data-pick]').nth(0).click();
  await page.locator('.record-card [data-pick]').nth(1).click();
  assert.equal(await page.evaluate(() => CinderLens.Store.state.picked.length), 2);
  await page.locator('.record-card [data-pick]').nth(2).click();
  assert.equal(await page.evaluate(() => CinderLens.Store.state.picked.length), 2);
  await page.locator('[data-action="compare-picked"]').click();
  await page.locator('.verdict').waitFor();
  await page.locator('[data-factor="oxygen_pct"]').click();
  assert.match(page.url(), /factor=oxygen_pct/);
  await page.reload();
  assert.equal(await page.locator('[data-factor="oxygen_pct"]').getAttribute('aria-pressed'), 'true');
  console.log('PASS mobile search, empty state, reset, focus trap, Escape, selection, handoff and refresh');
  await page.goto(base + '#/');
  await page.locator('.hero-actions [href="#/explorer"]').click();
  await page.goBack();
  await page.locator('.hero').waitFor();
  await page.goForward();
  await page.locator('#explorer-search').waitFor();
  assert.equal(await page.locator('.nav-link[aria-current="page"]').getAttribute('data-nav'), 'explorer');
  console.log('PASS skip link, browser back/forward and active navigation');
  await page.goto(base + '#/explorer?coverage=1');
  await page.locator('[data-coverage-fuel]').first().click();
  assert.ok((await page.evaluate(() => CinderLens.Store.activeFilterChips().length)) >= 2);
  await page.goto(base + '#/compare?a=UNKNOWN&b=&factor=bad-key');
  await page.getByText(/Unknown comparison factor/).waitFor();
  await page.goto(base + '#/evidence/BASS2-T137');
  await page.getByText('No media indexed for this run', {exact: true}).waitFor();
  await page.locator('#mode-chip').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#mode-chip').getAttribute('aria-expanded'), 'false');
  console.log('PASS coverage filter, invalid URL, missing media and popover Escape');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('.btn')).transitionDuration), '0s');
  assert.deepEqual(errors, []);
  await page.setViewportSize({width: 1440,height: 1000});
  await page.goto(base + '#/');
  await page.screenshot({path: path.join(process.env.TEMP, 'cinderlens-overview.png'), fullPage: true});
  await page.goto(base + routes[3]);
  await page.screenshot({path: path.join(process.env.TEMP, 'cinderlens-compare.png'), fullPage: true});
  await page.setViewportSize({width: 390,height: 844});
  await page.goto(base + '#/explorer');
  await page.evaluate(() => { CinderLens.Store.resetFilters(); CinderLens.App.renderRoute(CinderLens.Router.current()); });
  await page.screenshot({path: path.join(process.env.TEMP, 'cinderlens-mobile.png'), fullPage: true});
  console.log('PASS reduced motion and no browser JavaScript errors; screenshots saved to TEMP');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
